services:
    app.backend_product_search.query_conditions_provider:
        class: AppBundle\Service\BackendProductSearch\QueryConditionsProvider
        arguments: ["@doctrine.orm.default_entity_manager"]
